version: "3.8"
services:
  mcweb-mongodb:
    image: mcweb-mongo
    container_name: mcweb-mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME_FILE=/run/secrets/mongo_root_password
      - MONGO_INITDB_ROOT_PASSWORD_File=/run/secrets/mongo_root_user
      - MONGO_INITDB_DATABASE=mcweb
    volumes:
      - mcweb-data:/data/db
    ports:
      - 5002:27017
    secrets:
      - mongo_root_password
      - mongo_root_user
  client-server:
    image: mcweb-client
    container_name: mcweb-client-server
    environment:
      - CLIENT_PORT=80
      - BACKEND_ADDRESS=mcweb-backend:5001
    ports:
      - "80:80"
    depends_on:
      - mcweb-backend
  mcweb-backend:
    image: mcweb-backend
    container_name: mcweb-backend
    environment:
      - BACKEND_HOST=0.0.0.0
      - BACKEND_PORT=5001
    volumes:
      - mcweb-servers:/servers
    ports:
      - "5001:5001"
    depends_on:
      - mcweb-mongodb
    secrets:
      - mongo_password
      - mongo_user
volumes:
  mcweb-data:
    name: mcweb-data
  mcweb-servers:
    name: mcweb-servers
secrets:
  mongo_root_password:
    file: "./secrets/mongo_root_password.txt"
  mongo_root_user:
    file: "./secrets/mongo_root_user.txt"
  mongo_user:
    file: "./secrets/mongo_root_user.txt"
  mongo_password:
    file: "./secrets/mongo_root_password.txt"
